export const IS_LOADING = "IS_LOADING";
export const GET_SCHOOL_BOYS = "GET_SCHOOL_BOYS";
export const GET_LESSONS = "GET_LESSONS";
export const GET_COLUMN_VALUES = "GET_COLUMN_VALUES";
export const UPDATE_PRESENCE_STATUS = "UPDATE_PRESENCE_STATUS";